name: Tests
on:
  push:
  workflow_dispatch:
  
jobs:
  Test-Fibonacci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Compile solution
        run: javac solutions/Fibonacci.java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          path: solutions/Fibonacci.java
      - name: Build with Maven
        run: mvn clean package
      - name: Test 1
        run: time bash tasks/fibonacci/run.sh
      - name: Test 2
        run: time bash tasks/fibonacci/run.sh
      - name: Test 3
        run: time bash tasks/fibonacci/run.sh

  Test-Payment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Compile solution
        run: javac solutions/payment.java
      - name: Test 1
        run: time bash tasks/payment/run.sh
      - name: Test 2
        run: time bash tasks/payment/run.sh
      - name: Test 3
        run: time bash tasks/payment/run.sh


  Test-Navigation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          path: solutions/Fibonacci.java
      - name: Compile solution
        run: javac solutions/navigation.java

  Test-Histogram:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Compile solution
        run: javac solutions/Histogram.java
      - name: Test 1
        run: time bash tasks/histogram/run.sh
      - name: Test 2
        run: time bash tasks/histogram/run.sh
      - name: Test 3
        run: time bash tasks/histogram/run.sh
